### ISSUE TITLE
Incorrectly identifying binary files as a non-binary

### ISSUE THREAD

**Issue by JacobDB** [jonschlinkert/gulp-is-binary#2]
It's me again :)

Somehow this has stopped identifying files as binaries. I've tried it on multiple machines, multiple files and file types, and it's just always saying "nope, not a binary."

Here's the relevant portion of the task I'm trying to use:

```
// process HTML
var html = gulp.src([src + "/**/*", "!" + src + "{/assets,/assets/**}"])
    // prevent breaking on error
    .pipe(plumber({errorHandler: on_error}))
    // check if source is newer than destination
    .pipe(gulpif(!argv.dist, newer(html_directory)))
    // check if file is a binary
    .pipe(is_binary())
    // skip file if it's a binary
    .pipe(through.obj(function(file, enc, next) {
        console.log(file.path + ": " + file.isBinary());

        if (file.isBinary()) {
            next();
            return;
        }

        // go to next file
        next(null, file);
    }))
    // replace variables
    .pipe(file_include({
        prefix:   "@@",
        basepath: "@file",
        context: {
            name:           name,
            pwa_name:       pwa_name,
            pwa_short_name: pwa_short_name,
            theme_color:    theme_color,
            description:    description,
            version:        version,
            repository:     repository,
            license:        license,
        }
    }))
    // replace icon placeholders
    .pipe(replace(/(?:<icon:)([A-Za-z0-9\-\_][^:>]+)(?:\:([A-Za-z0-9\-\_\ ][^:>]*))?(?:>)/g, "<i class='icon $2'><svg class='icon_svg' aria-hidden='true'><use xlink:href='#$1' \/><\/svg></i>"))
    // output to compiled directory
    .pipe(gulp.dest(html_directory));
```

Which outputs:

```
...
/Users/jacob/Repositories/new-site/src/page.php: false
/Users/jacob/Repositories/new-site/src/partials: false
/Users/jacob/Repositories/new-site/src/screenshot.png: false /* here's the issue! */
/Users/jacob/Repositories/new-site/src/search.php: false
/Users/jacob/Repositories/new-site/src/searchform.php: false
...
```

This used to work perfectly, but now it's mangling my image files. Nothing has changed, so I'm at a loss. 

Any idea what might be happening?

**Comment by JacobDB** [comment]
Thought it might have something to do with naming my variable `is_binary` instead of `isBinary`, but that didn't make any difference in testing.

**Comment by JacobDB** [comment]
So, this is weird. It's saying my screenshot.png is encoded in utf8, but that can't be right, can it...?

Using this in my task now: `console.log(file.path + ": " + enc);`

    /Users/jacob/Repositories/new-site/src/screenshot.png: utf8

Further testing, even trying .dll files are listed as utf8. I'm so confused.

    /Users/jacob/Repositories/new-site/DevExpress.Data.v9.2.dll: utf8

**Comment by JacobDB** [comment]
Further testing shows that it's likely an updated module causing this problem. I'm going to hunt through the dependencies until I find which one.

**Comment by JacobDB** [comment]
After doing a bit of research, I see two dependencies that have been updated since my last-known-working-date of 2017-02-20.

- [is-buffer](https://github.com/feross/is-buffer)
- [readable-stream](https://github.com/nodejs/readable-stream)

I suspect is-buffer more than readable-stream, but my next step is to install a version of each from on or before 2017-02-20 and see if that fixes the problem.

```
├─┬ gulp-is-binary@0.1.2           — https://github.com/jonschlinkert/gulp-is-binary       — NOT IT
│ └─┬ file-is-binary@0.2.2         — https://github.com/jonschlinkert/file-is-binary       — NOT IT
│   ├─┬ file-stat@1.0.0            - https://github.com/jonschlinkert/file-stat            — NOT IT
│   │ ├── fs-exists-sync@0.1.0     — https://github.com/jonschlinkert/fs-exists-sync       — NOT IT
│   │ ├── graceful-fs@4.1.11       — https://github.com/isaacs/node-graceful-fs            — NOT IT
│   │ └─┬ lazy-cache@2.0.2         — https://github.com/jonschlinkert/lazy-cache           — NOT IT
│   │   └─┬ set-getter@0.1.0       — https://github.com/doowb/set-getter                   — NOT IT
│   │     └─┬ to-object-path@0.3.0 — https://github.com/jonschlinkert/to-object-path       — NOT IT
│   │       └─┬ kind-of@3.1.0      — https://github.com/jonschlinkert/kind-of              — NOT IT 
│   │         └── is-buffer@1.1.5  — https://github.com/feross/is-buffer                   — POSSIBILITY
│   ├── isbinaryfile@3.0.2         — https://github.com/gjtorikian/isBinaryFile            — NOT IT
│   └── isobject@3.0.0             — https://github.com/jonschlinkert/isobject             — NOT IT
└─┬ through2@2.0.3                 — https://github.com/rvagg/through2                     — NOT IT
  ├─┬ readable-stream@2.2.6        — https://github.com/nodejs/readable-stream             — POSSIBILITY
  │ ├── buffer-shims@1.0.0         — https://github.com/calvinmetcalf/buffer-shims         — NOT IT
  │ ├── core-util-is@1.0.2         — https://github.com/isaacs/core-util-is                — NOT IT
  │ ├── inherits@2.0.3             — https://github.com/isaacs/inherits                    — NOT IT
  │ ├── isarray@1.0.0              — https://github.com/juliangruber/isarray               — NOT IT
  │ ├── process-nextick-args@1.0.7 — https://github.com/calvinmetcalf/process-nextick-args — NOT IT
  │ ├── string_decoder@0.10.31     — https://github.com/rvagg/string_decoder               — NOT IT
  │ └── util-deprecate@1.0.2       — https://github.com/TooTallNate/util-deprecate)        — NOT IT
  └── xtend@4.0.1                  — https://github.com/Raynos/xtend                       — NOT IT
```

**Comment by JacobDB** [comment]
Alright, so installing `is-buffer@1.1.4` and `readable-stream@2.2.2` didn't work in any configuration. Guess I'll have to come back to this tomorrow.

**Comment by JacobDB** [comment]
I was able to confirm this was working on an older project, but when I `rm -rf`'d the modules and re-installed, I'm now getting the same error. So I'm pretty sure it's not something to do with my particular setup, since literally nothing changed between that.

**Comment by jonschlinkert** [comment]
strange, thanks for looking into it. Hmm, have you tried directly using [file-is-binary](https://github.com/jonschlinkert/file-is-binary) on one of the files in question? I would expect that to fail as well

**Comment by JacobDB** [comment]
Huh, file-is-binary on its own is detecting that the file is a binary properly.

**Comment by JacobDB** [comment]
I just wrote the simplest gulp test I could, and it's acting exactly as it is for my actual gulpfile. I've attached the test to this comment. I also included the file-is-binary test as well. Simply download the zip, run `npm i`, then `gulp` or `node index.js`. You'll see it does not detect a binary for the gulp test, but does for the node test.

[binary-test.zip](https://github.com/jonschlinkert/gulp-is-binary/files/850712/binary-test.zip)

**Comment by JacobDB** [comment]
I've moved the ZIP in to a repository: https://github.com/JacobDB/gulp-is-binary-testing

**Comment by jonschlinkert** [comment]
Ok, I figured out the cause. in `file-is-binary`, the logic that checked if a file was a stream was returning a false-negative with older vinyl files. should be fixed now. thanks for making this easy to test and work through, I appreciate your patience.

**Comment by JacobDB** [comment]
No problem, thanks for fixing it!

**Comment by JacobDB** [comment]
Just had a chance to test this morning, can verify it's now working as expected. Thanks again!
